package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3cl/opencl/cl"
	"github.com/mumax/3cl/timer"
	"sync"
)


// Stores the arguments for finaltwiddlefact kernel invocation
type finaltwiddlefact_args_t struct{
	 arg_dataOut unsafe.Pointer
	 arg_origlength int
	 arg_extenlength int
	 arg_fftdirec int
	 arg_offset int
	 argptr [5]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for finaltwiddlefact kernel invocation
var finaltwiddlefact_args finaltwiddlefact_args_t

func init(){
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	 finaltwiddlefact_args.argptr[0] = unsafe.Pointer(&finaltwiddlefact_args.arg_dataOut)
	 finaltwiddlefact_args.argptr[1] = unsafe.Pointer(&finaltwiddlefact_args.arg_origlength)
	 finaltwiddlefact_args.argptr[2] = unsafe.Pointer(&finaltwiddlefact_args.arg_extenlength)
	 finaltwiddlefact_args.argptr[3] = unsafe.Pointer(&finaltwiddlefact_args.arg_fftdirec)
	 finaltwiddlefact_args.argptr[4] = unsafe.Pointer(&finaltwiddlefact_args.arg_offset)
	 }

// Wrapper for finaltwiddlefact OpenCL kernel, asynchronous.
func k_finaltwiddlefact_async ( dataOut unsafe.Pointer, origlength int, extenlength int, fftdirec int, offset int,  cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous{ // debug
		ClCmdQueue.Finish()
		timer.Start("finaltwiddlefact")
	}

	finaltwiddlefact_args.Lock()
	defer finaltwiddlefact_args.Unlock()

	 finaltwiddlefact_args.arg_dataOut = dataOut
	 finaltwiddlefact_args.arg_origlength = origlength
	 finaltwiddlefact_args.arg_extenlength = extenlength
	 finaltwiddlefact_args.arg_fftdirec = fftdirec
	 finaltwiddlefact_args.arg_offset = offset
	

	SetKernelArgWrapper("finaltwiddlefact", 0, dataOut)
	SetKernelArgWrapper("finaltwiddlefact", 1, origlength)
	SetKernelArgWrapper("finaltwiddlefact", 2, extenlength)
	SetKernelArgWrapper("finaltwiddlefact", 3, fftdirec)
	SetKernelArgWrapper("finaltwiddlefact", 4, offset)
	

//	args := finaltwiddlefact_args.argptr[:]
	event := LaunchKernel("finaltwiddlefact", cfg.Grid, cfg.Block, events)

	if Synchronous{ // debug
		ClCmdQueue.Finish()
		timer.Stop("finaltwiddlefact")
	}

	return event
}

